apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-easytravel"
spec:
  stages:
    - name: "quality-gate"
      sequences:
        - name: deployment
          tasks:
            - name: deployment
              properties:
                deploymentstrategy: direct
        - name: testing
          triggeredOn:
            - event: "quality-gate.delivery.finished"
          tasks:
            - name: "test"
              properties:
                teststrategy: "performance_5"
            - name: "evaluation"

