apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-easytravel"
spec:
  stages:
    - name: "quality-gate"
      sequences:
        - name: "testing"
          triggeredOn:
            - event: "sh.keptn.events.deployment-finished"
          tasks:
            - name: "test"
              properties:
                teststrategy: "performance_5"
            - name: "evaluation"
