apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-easytravel"
spec:
  stages:
  - name: "quality-gate"
    sequences:
    - name: delivery
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: direct
    - name: testing
      triggeredOn:
      - event: quality-gate.delivery.finished
        selector:
          match:
            result: pass
      tasks:
      - name: tests
        properties:
          teststrategy: performance
      - name: evaluation

