apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
    - name: "quality-gate"
      sequences:
      - name: "delivery"
        tasks:
        - name: "deployment"
          properties: 
            deploymentstrategy: direct
        - name: "test"
          properties:
            teststrategy: performance
        - name: evaluation
